DATASET:
  BATCH_SIZE: 64
  CROP_FACTOR: 0.5
  CROP_PROB: 0.0
  FLIP_PROB: 0.5
  FOCAL_LENGTH: 5000.0
  IGNORE_3D: false
  IMG_RES: 224
  LOAD_TYPE: Base
  MESH_COLOR: pinkish
  NOISE_FACTOR: 0.4
  NUM_IMAGES: -1
  NUM_WORKERS: -1
  OCC_AUG_DATASET: pascal
  PIN_MEMORY: true
  RENDER_RES: 480
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  TRAIN_DS: all
  USE_3D_CONF: true
  USE_GENDER: true
  USE_HEATMAPS: part_segm
  USE_SYNTHETIC_OCCLUSION: true
  VAL_DS: 3doh_3dpw-all
EXP_NAME: pare_w_3dpw
LOG_DIR: logs/pare_w_3dpw
METHOD: pare
OPTIMIZER:
  LR: 5.0e-05
  TYPE: adam
  WD: 0.0
PARE:
  BACKBONE: hrnet_w32-conv
  BETA_LOSS_WEIGHT: 0.0
  BRANCH_DEEPER: false
  COATTENTION_CONV: simple
  DECONV_CONV_KERNEL_SIZE: 4
  GT_TRAIN_WEIGHT: 1.0
  HEATMAPS_LOSS_WEIGHT: 50.0
  INIT_XAVIER: false
  ITERATIVE_REGRESSION: false
  ITER_RESIDUAL: false
  KEYPOINT_ATTENTION_ACT: softmax
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  NUM_BRANCH_ITERATION: 0
  NUM_COATTENTION_ITER: 1
  NUM_DECONV_FILTERS: 128
  NUM_DECONV_LAYERS: 2
  NUM_FEATURES_SMPL: 64
  NUM_ITERATIONS: 3
  NUM_JOINTS: 24
  OPENPOSE_TRAIN_WEIGHT: 0.0
  PART_SEGM_LOSS_WEIGHT: 0.0
  POSE_INPUT_TYPE: feats.self_pose.shape.cam
  POSE_LOSS_WEIGHT: 1.0
  POSE_MLP_HIDDEN_SIZE: 256
  POSE_MLP_NUM_LAYERS: 1
  SHAPE_INPUT_TYPE: feats.shape.cam
  SHAPE_LOSS_WEIGHT: 0
  SHAPE_MLP_HIDDEN_SIZE: 256
  SHAPE_MLP_NUM_LAYERS: 1
  SMPL_PART_LOSS_WEIGHT: 1.0
  SOFTMAX_TEMP: 1.0
  USE_ATTENTION: false
  USE_BRANCH_NONLOCAL: null
  USE_COATTENTION: false
  USE_FINAL_NONLOCAL: null
  USE_HMR_REGRESSION: false
  USE_KEYPOINT_ATTENTION: true
  USE_KEYPOINT_FEATURES_FOR_SMPL_REGRESSION: false
  USE_MEAN_CAMSHAPE: false
  USE_MEAN_POSE: false
  USE_POSTCONV_KEYPOINT_ATTENTION: false
  USE_POS_ENC: false
  USE_RESNET_CONV_HRNET: false
  USE_SCALE_KEYPOINT_ATTENTION: false
  USE_SELF_ATTENTION: false
  USE_SHAPE_REG: true
  USE_SOFT_ATTENTION: false
  USE_UPSAMPLING: false
PROJECT_NAME: pare
RUN_TEST: false
SEED_VALUE: -1
TESTING:
  MULTI_SIDEVIEW: false
  SAVE_FREQ: 1
  SAVE_IMAGES: false
  SAVE_MESHES: false
  SAVE_RESULTS: true
  SIDEVIEW: true
  TEST_ON_TRAIN_END: true
  USE_GT_CAM: false
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  DROPOUT_P: 0.2
  LOG_FREQ_TB_IMAGES: 2000
  LOG_SAVE_INTERVAL: 50
  MAX_EPOCHS: 100
  NUM_SMPLIFY_ITERS: 100
  PRETRAINED: null
  PRETRAINED_LIT: data/pare/checkpoints/pare_w_3dpw_checkpoint.ckpt
  RELOAD_DATALOADERS_EVERY_EPOCH: true
  RESUME: null
  RUN_SMPLIFY: false
  SAVE_IMAGES: true
  SMPLIFY_THRESHOLD: 100
  TEST_BEFORE_TRAINING: false
  USE_AMP: false
  USE_PART_SEGM_LOSS: false
